GET http://localhost:3000/orders/1

###

GET http://localhost:3000/products/category/1

###

GET http://localhost:3000/cart/2

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "user3",
    "password": "12345",
    "address": "test address"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "user3",
    "password": "12345"
}

###

POST http://localhost:3000/users/logout

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "productName": "Surging Sparks Elite Trainer Box",
    "productCost": "50.00",
    "productDescription": "Elite Trainer Box released for the Surging Sparks expansion.",
    "productQuantity": "20",
    "productOwnerId": "4"
}

###

POST http://localhost:3000/cart/2
Content-Type: application/json

{
    "productId": "5",
    "quantity": "3",
    "totalCost": "150.00"
}

###

POST http://localhost:3000/cart/2/checkout
Content-Type: application/json

{
    "userId": "5",
    "deliveryAddress": "17 Grosvenor Court, Sutton, London"
}

###

PUT http://localhost:3000/users/4
Content-Type: application/json

{
    "username": "poopdetangs",
    "password": "123456",
    "address": "Sutton"
}

###

DELETE http://localhost:3000/cart/10